### ISSUE TITLE
Native Android App

### ISSUE THREAD

**Issue by Vixeliz** [bridge-core/editor#256]
**Summary**
A native android app

**Alternatives/Considerations**
The progressive web app already kind of fills this category but i find it can be buggy, doesnt work well offline, and saving projects is a hassle compared to a native android version.

**Additional context/Motivation**
Being able to have a full dev environment for minecraft on android would be nice for people who use android as their primary os as i do. The main improvement as said is project saving is very tedious through the pwa.

**Comment by solvedDev** [comment]
We do not have the development resources to work on native apps for Android/iOS. Our small team already struggles to maintain the single codebase for the web app.

- Buggy experience: Please report the bugs you experience instead of just telling us that it's buggy. That's not helpful
- Why doesn't it work offline? I personally didn't experience offline problems at all
- File saving is on the Chrome for Android team to implement. It works as expected on desktop platforms. To make the app available on all platforms, we have developed this replacement technology.

**Comment by Vixeliz** [comment]
Sorry just saw this. I completly understand that it is too much work for this team. As for bugs i dont really know how to explain its just small things like a file not creating or some ui being messed up etc. The offline issue has seemed to fix itself the problem was no projects could be created offline but it seems to work now. As for the project saving is their any plans for it to come to android?

**Comment by solvedDev** [comment]
As already mentioned, "real" file saving is up to the Chrome for Android team to implement. In the meantime, our current workarounds are the best possible solutions imo

**Comment by Vixeliz** [comment]
Oh sorry i mis understood alright thank you

**Comment by solvedDev** [comment]
np :)
