### ISSUE TITLE
Can not disable software acceleration separately

### ISSUE THREAD

**Issue by Endermanbugzjfc** [bridge-core/editor#294]
**Summary**
Why is this thing even slower than IntelliJ IDEA Ultimate with 40 plugins running. Every action, create a new file, load the new file is laggy. I want to disable software acceleration, but since v2, the app is browser-bundled. If I disable software acceleration for the editor, it is going to do it for the whole browser.

**To Reproduce**
1. Go to Chrome setting
2. Disable 'Use hardware acceleration when available'

**Observed behavior**
Hardware acceleration is disabled for the browser.
**Expected behavior**
Hardware acceleration is disabled for the editor.

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**
 - OS: MacOS 12.1
 - App Version: [e.g. 2.1.5]

**Additional context**

**Comment by solvedDev** [comment]
There's nothing we can do about this atm, leaving the issue open regardless to track the problem

**Comment by jasonjgardner** [comment]
It's slower than IntelliJ IDEA Ultimate because JetBrains has over 1000 paid employees working on its IDE... and bridge. v2 relies on a bleeding-edge JavaScript API to access your computer's filesystem. This isn't an issue exclusive to bridge. though. It's sort of the state of PWAs for now.

Hardware acceleration is not going to do much for you with bridge. anyway. Go to `chrome://gpu/` to check your browser's Graphics Feature Status. If any Canvas, WebGL, or rasterization features are not labeled "Enabled" then your system is unable to make a difference in the few features potentially used by bridge.

**Comment by jasonjgardner** [comment]
You could consider installing bridge. from another Chromium browser with no extensions installed to improve performance. Chrome loads its browser extensions in PWAs too. A bunch of browser extensions could bog down a web app like bridge.

**Comment by solvedDev** [comment]
We have done massive performance optimizations to our editor for the upcoming bridge. v2.3 update. Those changes should resolve most of the issues you've talked about
