### ISSUE TITLE
General "Experimental" Toggle for projects

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#325]
**Summary**
A general "Experimental" toggle for entire projects would be nice, apart from being able to select which experimental features should be enabled. That way, bridge. can provide correct autocompletions for things like events, where currently, on higher format versions, the `run_command` feature is recommended, even though none of the experimental features are enabled. 
The experimental toggle should also be able to be queried by compiler plugins, custom components and presets, to be able to have presets that only show up for experimental packs (like +1.16 blocks).

**Alternatives/Considerations**
None

**Additional context/Motivation**
This would be especially useful when developing for Marketplace, making sure that experimental features weren't used accidentally.

**Comment by solvedDev** [comment]
The ideal solution would be to use the existing experimental gameplay toggles wherever possible imo. An additional toggle could be confusing and auto-completions should already be toggleable just fine with the existing toggles. If this doesn't work in specific areas, please report that as separate issues.
(@Joelant05 already fixed your specific event example if I read the commit earlier today correctly)

As for exposing experimental gameplay inside of the compiler: This is already done because we expose the whole project config as "projectConfig".

Presets can also already be toggled based on experimental gameplay.
