### ISSUE TITLE
min_engine_version too high

### ISSUE THREAD

**Issue by mcd912** [bridge-core/editor#433]
When I try to test my packs, they weren't showing in the available list, although the files were in the dev pack folders.  Tried to package as addon to see if it would work in the pack folders and got this error:

The property '/header/min_engine_version' has a version of '1.19.0' which is too high. The highest value we accept is '1.18.31'.

**Comment by Joelant05** [comment]
To get them to show you need to lower the "min_engine_version" field in the manifests in your project. You should also lower the "targetVersion" in your project config.
I'm going to close this issue due to this not being a bug, just make sure to set your project target version correctly at project creation
