### ISSUE TITLE
[Render Dragon] Add support for new material bin files

### ISSUE THREAD

**Issue by StealthyExpertX** [bridge-core/editor#439]
**Summary**
_Please add support for material bin files so we can edit shaders and other material effects._

_There are new matieral.bin files at the root Minecraft Bedrock Folder's location in the path_ **"renderer/materials"**.

![image](https://user-images.githubusercontent.com/17806994/167186320-7e7eb37e-dabd-4145-b190-e3352bd3b74d.png)

_mats.zip contains lots of sample files from vanilla._
https://www.mediafire.com/file/okezbgpoc5drmmx/mats.zip/file

_Message me if you need help, I'm willing to volunteer my time researching/testing with your team to help with this.

**Alternatives/Considerations**
_I tried reverse-engineering the file format but due to me being very rusty at file engineering I do not think I have the required skill sets anymore to accomplish this._

**Additional context/Motivation**
_My reasoning is allowing support for these files may allow us to create custom shaders, custom animated cubemaps, and many other fantastic shader-type effects or new custom entity materials!_

**Comment by StealthyExpertX** [comment]
For more information, to decompile and recompile these files here is a decompiler/recompile utility somebody made, though some manual translation is needed.
https://github.com/ddf8196/MaterialBinTool

Also, you can follow these steps for performing an edit.

DECOMPILED FILES:
https://cdn.discordapp.com/attachments/970211028984029217/970655237922754600/Render_Dragon_Default_Shaders.zip

Step 1: Use materialbintool on shader bin files to decompile

Step 2: Edit files and repack to the bin.

Step 3: Rename .apk to .zip and unzip and extract to any folder directory.

Step 4: Replace bin files in "materials"

**Comment by StealthyExpertX** [comment]
Disclaimer, This info is provided from a Render Dragon Discord.

**Comment by StealthyExpertX** [comment]
Precompiled render dragon files
[renderer.zip](https://github.com/bridge-core/editor/files/8645115/renderer.zip)
.

**Comment by Joelant05** [comment]
This is the first time of me hearing of this so let me know if I'm misunderstanding something here, but here are my thoughts: 
- I don't think this fits into something that bridge. should support
- As far as I can see these can only be modified from the game assets directory, not through Add-Ons, at least for now
- I believe we should wait for custom RD materials to officially be supported before we work on supporting them
- This decompiling and recompiling of shaders seems like something that could be prevented by Mojang in the future and it could be a lot of work and time invested into something that could stop working at anytime
- The tool linked [here](https://github.com/ddf8196/MaterialBinTool) is written in Java and would take a lot of time to rewrite the algorithm into TS

I'll close this issue because of the reasons listed above. As I said, lmk if I've got anything wrong here
