### ISSUE TITLE
Import File: File type guessing not working

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#542]
The path seems to always be set to `SP/skins.json/`. Not sure if this only applies for certain files but with the VP viewer at least, selecting "Import to Pack" and "Save to Project" will always show the wrong path.

Perhaps due to https://github.com/bridge-core/editor-packages/commit/5ee2701d3d3324318fba1836b4bc8859de69a46f and the addition of "fileExtensions" to every file definition

**Comment by solvedDev** [comment]
We in fact have to rewrite file type guessing because of this change. I've been playing around with making this even better anyways though (basically going through every condition one by one and then reduce the set of valid file types further and further until we only have one match instead of returning the first match for any condition)
