### ISSUE TITLE
Custom block component doesn't compile

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/editor#544]
**Summary**
https://discord.com/channels/602097536404160523/602097536840237087/1002562527152050176

**To Reproduce**
https://github.com/FrederoxDev/Cosmos-Genesis

**Comment by FrederoxDev** [comment]
I have created a branch so that I can remove the custom components temporarily on my main branch

**To reproduce** https://github.com/FrederoxDev/Cosmos-Genesis/tree/bridge-issue-544

**Comment by FrederoxDev** [comment]
@solvedDev I believe I have found the cause of the issue. 

I believe it to be caused by bridge not updating the config.json file to include the "generatorScripts" plugin.

I discovered this by creating a new project in bridge and moving over the old addon files, and comparing the changes detected by git. By including this plugin custom components now work again in the original project

**Comment by FrederoxDev** [comment]
Weird this may not be the cause, the issue has just came back in my original project

**Comment by solvedDev** [comment]
I've downloaded your repo and compiled the project with bridge. but custom components immediately compiled fine (without making further changes) so I am going to close this issue as "Cannot Reproduce". I am aware that the standalone dash compiler is having some issues rn though which we need to look into
